version: '3.8'

volumes:
  postgres_data:
    driver: local
  arango_data:
    driver: local

services:
  postgres:
    image: postgres:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test123
      TZ: Europe/Moscow
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    deploy:
      replicas: 1
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.ru"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"

  arangodb:
    image: arangodb:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - arango_data:/var/lib/arangodb3
    environment:
      ARANGO_ROOT_PASSWORD: test123
      ARANGO_JWT_SECRET: test123
      TZ: Europe/Moscow
    ports:
      - "8529:8529"